# Import Libraries

In [178]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Import the Dataset

In [179]:
fish_dataset = pd.read_csv('Fish Market.csv')
x = fish_dataset.iloc[:, 1:].values
y = fish_dataset.iloc[:, 0].values
fish_dataset.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [180]:
pd.set_option('display.max_rows', None)
print(fish_dataset.describe())

            Weight     Length1     Length2     Length3      Height       Width
count   159.000000  159.000000  159.000000  159.000000  159.000000  159.000000
mean    398.326415   26.247170   28.415723   31.227044    8.970994    4.417486
std     357.978317    9.996441   10.716328   11.610246    4.286208    1.685804
min       0.000000    7.500000    8.400000    8.800000    1.728400    1.047600
25%     120.000000   19.050000   21.000000   23.150000    5.944800    3.385650
50%     273.000000   25.200000   27.300000   29.400000    7.786000    4.248500
75%     650.000000   32.700000   35.500000   39.650000   12.365900    5.584500
max    1650.000000   59.000000   63.400000   68.000000   18.957000    8.142000


In [181]:
with np.printoptions(threshold=np.inf):
  print(x)

[[ 242.     23.2    25.4    30.     11.52    4.02]
 [ 290.     24.     26.3    31.2    12.48    4.31]
 [ 340.     23.9    26.5    31.1    12.38    4.7 ]
 [ 363.     26.3    29.     33.5    12.73    4.46]
 [ 430.     26.5    29.     34.     12.44    5.13]
 [ 450.     26.8    29.7    34.7    13.6     4.93]
 [ 500.     26.8    29.7    34.5    14.18    5.28]
 [ 390.     27.6    30.     35.     12.67    4.69]
 [ 450.     27.6    30.     35.1    14.      4.84]
 [ 500.     28.5    30.7    36.2    14.23    4.96]
 [ 475.     28.4    31.     36.2    14.26    5.1 ]
 [ 500.     28.7    31.     36.2    14.37    4.81]
 [ 500.     29.1    31.5    36.4    13.76    4.37]
 [ 340.     29.5    32.     37.3    13.91    5.07]
 [ 600.     29.4    32.     37.2    14.95    5.17]
 [ 600.     29.4    32.     37.2    15.44    5.58]
 [ 700.     30.4    33.     38.3    14.86    5.29]
 [ 700.     30.4    33.     38.5    14.94    5.2 ]
 [ 610.     30.9    33.5    38.6    15.63    5.13]
 [ 650.     31.     33.5    38.

In [182]:
print(x.shape)

(159, 6)


In [183]:
with np.printoptions(threshold=np.inf):
  print(y)

['Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream'
 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream'
 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream'
 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Roach'
 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach'
 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach'
 'Roach' 'Whitefish' 'Whitefish' 'Whitefish' 'Whitefish' 'Whitefish'
 'Whitefish' 'Parkki' 'Parkki' 'Parkki' 'Parkki' 'Parkki' 'Parkki'
 'Parkki' 'Parkki' 'Parkki' 'Parkki' 'Parkki' 'Perch' 'Perch' 'Perch'
 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch'
 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch'
 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch'
 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch'
 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch'

# Data Preprocessing Stage 

# Encoding Categorical Features (columns) into numeric values for use in regression

In [184]:
print(y)
y = y.reshape(-1, 1)
print(y)

['Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream'
 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream'
 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream'
 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Roach'
 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach'
 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach'
 'Roach' 'Whitefish' 'Whitefish' 'Whitefish' 'Whitefish' 'Whitefish'
 'Whitefish' 'Parkki' 'Parkki' 'Parkki' 'Parkki' 'Parkki' 'Parkki'
 'Parkki' 'Parkki' 'Parkki' 'Parkki' 'Parkki' 'Perch' 'Perch' 'Perch'
 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch'
 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch'
 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch'
 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch'
 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch'

In [185]:
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()
y = le.fit_transform(y)

/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [186]:
with np.printoptions(threshold=np.inf):
  print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 6 6 6 6 6 6 1 1 1 1 1 1 1 1 1 1 1 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 5 5 5
 5 5 5 5 5 5 5 5 5 5 5]


# Split the Dataset into Training set and Test set

In [187]:
from sklearn.model_selection import train_test_split
fish_x_train, fish_x_test, fish_y_train, fish_y_test = train_test_split(x, y, test_size=0.3, random_state = 1)
np.set_printoptions(suppress=True)
print(fish_x_train)

[[ 272.     25.     27.     30.6     8.57    4.77]
 [ 650.     36.5    39.     41.4    11.14    6.  ]
 [ 540.     40.1    43.     45.8     7.79    5.13]
 [ 700.     30.4    33.     38.5    14.94    5.2 ]
 [ 100.     16.2    18.     19.2     5.22    3.32]
 [  19.7    13.2    14.3    15.2     2.87    2.07]
 [ 340.     29.5    32.     37.3    13.91    5.07]
 [  78.     16.8    18.7    19.4     5.2     3.12]
 [ 610.     30.9    33.5    38.6    15.63    5.13]
 [ 169.     22.     24.     27.2     7.53    3.84]
 [ 150.     20.5    22.5    24.      6.79    3.62]
 [ 430.     26.5    29.     34.     12.44    5.13]
 [ 160.     20.5    22.5    25.3     7.03    3.82]
 [1250.     52.     56.     59.7    10.69    6.98]
 [ 120.     18.6    20.     22.2     6.22    3.57]
 [  69.     16.5    18.2    20.3     5.3     2.82]
 [1000.     40.2    43.5    46.     12.6     8.14]
 [   7.     10.1    10.6    11.6     1.73    1.15]
 [  10.     11.3    11.8    13.1     2.21    1.28]
 [   7.5    10.     10.5    11.

# Machine Learning Stage 

# Create the Polynomial model on the training set

In [188]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 4)
x_poly = poly_reg.fit_transform(fish_x_train)

# Train Model

In [189]:
lin_reg = LinearRegression()
lin_reg.fit(x_poly, fish_y_train)

LinearRegression()

# Test the Model

In [190]:
print(fish_x_test)

[[1000.     33.5    37.     42.6    18.96    6.6 ]
 [ 120.     19.4    21.     23.7     6.11    3.29]
 [ 600.     29.4    32.     37.2    14.95    5.17]
 [ 130.     20.5    22.5    24.      5.86    3.62]
 [  85.     18.2    20.     21.      5.08    2.77]
 [ 650.     31.     33.5    38.7    14.47    5.73]
 [ 145.     20.5    22.     24.3     6.63    3.55]
 [ 500.     28.7    31.     36.2    14.37    4.81]
 [   0.     19.     20.5    22.8     6.48    3.35]
 [ 145.     22.     24.     25.5     6.38    3.83]
 [ 135.     20.     22.     23.5     5.88    3.52]
 [ 150.     21.     23.     24.5     5.22    3.63]
 [  32.     12.5    13.7    14.7     3.53    2.  ]
 [ 250.     25.4    27.5    28.9     7.28    4.57]
 [ 800.     33.7    36.4    39.6    11.76    6.57]
 [ 110.     20.     22.     23.5     5.52    4.  ]
 [ 140.     19.     20.7    23.2     8.54    3.29]
 [ 390.     29.5    31.7    35.      9.48    5.36]
 [ 320.     27.8    30.     31.6     7.62    4.77]
 [ 197.     23.5    25.6    27.

# Compare the test set predictions with the actual values

In [191]:
print(fish_y_test)

[0 4 0 2 2 0 4 0 4 2 2 2 2 2 6 2 1 4 2 2 5 4 4 0 2 0 0 5 3 2 2 2 2 3 6 2 4
 1 0 6 3 2 2 5 0 2 2 0]


In [192]:
y_poly_pred = lin_reg.predict(poly_reg.fit_transform(fish_x_test))
print(y_poly_pred)

[-105.66    5.68   -8.77    1.88    3.4   -26.31    2.73   -4.      2.22
    1.8     2.36    3.35    2.66   -0.36  -42.82    0.02    1.42   -0.72
    2.66   -0.31    5.21    7.16    4.33    5.69    2.83    5.71   -8.11
    4.55 -237.39    2.16  -86.53    1.36  124.47    1.75   38.23    9.63
    2.35    1.31 -199.      6.08    2.41   30.1     3.71    4.9    24.4
   -2.15   -0.12   -9.17]


In [193]:
np.set_printoptions(precision=2)
print(np.concatenate((y_poly_pred.reshape(len(y_poly_pred), 1), fish_y_test.reshape(len(fish_y_test), 1)), 1))

[[-105.66    0.  ]
 [   5.68    4.  ]
 [  -8.77    0.  ]
 [   1.88    2.  ]
 [   3.4     2.  ]
 [ -26.31    0.  ]
 [   2.73    4.  ]
 [  -4.      0.  ]
 [   2.22    4.  ]
 [   1.8     2.  ]
 [   2.36    2.  ]
 [   3.35    2.  ]
 [   2.66    2.  ]
 [  -0.36    2.  ]
 [ -42.82    6.  ]
 [   0.02    2.  ]
 [   1.42    1.  ]
 [  -0.72    4.  ]
 [   2.66    2.  ]
 [  -0.31    2.  ]
 [   5.21    5.  ]
 [   7.16    4.  ]
 [   4.33    4.  ]
 [   5.69    0.  ]
 [   2.83    2.  ]
 [   5.71    0.  ]
 [  -8.11    0.  ]
 [   4.55    5.  ]
 [-237.39    3.  ]
 [   2.16    2.  ]
 [ -86.53    2.  ]
 [   1.36    2.  ]
 [ 124.47    2.  ]
 [   1.75    3.  ]
 [  38.23    6.  ]
 [   9.63    2.  ]
 [   2.35    4.  ]
 [   1.31    1.  ]
 [-199.      0.  ]
 [   6.08    6.  ]
 [   2.41    3.  ]
 [  30.1     2.  ]
 [   3.71    2.  ]
 [   4.9     5.  ]
 [  24.4     0.  ]
 [  -2.15    2.  ]
 [  -0.12    2.  ]
 [  -9.17    0.  ]]


# Making a Single Prediction

In [194]:
with np.printoptions(threshold=np.inf):
  print(x)

[[ 242.     23.2    25.4    30.     11.52    4.02]
 [ 290.     24.     26.3    31.2    12.48    4.31]
 [ 340.     23.9    26.5    31.1    12.38    4.7 ]
 [ 363.     26.3    29.     33.5    12.73    4.46]
 [ 430.     26.5    29.     34.     12.44    5.13]
 [ 450.     26.8    29.7    34.7    13.6     4.93]
 [ 500.     26.8    29.7    34.5    14.18    5.28]
 [ 390.     27.6    30.     35.     12.67    4.69]
 [ 450.     27.6    30.     35.1    14.      4.84]
 [ 500.     28.5    30.7    36.2    14.23    4.96]
 [ 475.     28.4    31.     36.2    14.26    5.1 ]
 [ 500.     28.7    31.     36.2    14.37    4.81]
 [ 500.     29.1    31.5    36.4    13.76    4.37]
 [ 340.     29.5    32.     37.3    13.91    5.07]
 [ 600.     29.4    32.     37.2    14.95    5.17]
 [ 600.     29.4    32.     37.2    15.44    5.58]
 [ 700.     30.4    33.     38.3    14.86    5.29]
 [ 700.     30.4    33.     38.5    14.94    5.2 ]
 [ 610.     30.9    33.5    38.6    15.63    5.13]
 [ 650.     31.     33.5    38.

In [195]:
lin_reg.predict(poly_reg.fit_transform([[242,23.2,25.4,30,11.52,4.02]]))

array([-0.])